# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     restart: always
#     environment:
#       - NODE_ENV=development
#     command: npm start

version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
